[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm config set enable-pre-post-scripts true", "pnpm install:all"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "cd server && node dist/index.js"
